"""
Django settings for curaciones project.

Generated by "django-admin startproject" using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from pathlib import Path
from typing import List, Dict, Tuple
import os

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR:Path = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY:str = "django-insecure-6%z0a)z1!s1)^9!mew&es^^*m#0k+u-%houj#sc0-w#q=l_#^)"

# SECURITY WARNING: don"t run with debug turned on in production!
DEBUG:bool = True

# ALLOWED_HOSTS:List[str] = ["localhost", "127.0.0.1"]
ALLOWED_HOSTS:List[str] = ["*"]

# Application definition
DJANGO_APPS:List[str] = [
   "django.contrib.admin",
   "django.contrib.auth",
   "django.contrib.contenttypes",
   "django.contrib.sessions",
   "django.contrib.messages",
   "django.contrib.staticfiles"
]
THIRD_PARTY_APPS:List[str] = [
   "sass_processor"
]
LOCAL_APPS:List[str] = [
   "core.apps.CoreConfig"
]
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE:List[str] = [
   "django.middleware.security.SecurityMiddleware",
   "django.contrib.sessions.middleware.SessionMiddleware",
   "django.middleware.common.CommonMiddleware",
   "django.middleware.csrf.CsrfViewMiddleware",
   "django.contrib.auth.middleware.AuthenticationMiddleware",
   "django.contrib.messages.middleware.MessageMiddleware",
   "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF:str = "curaciones.urls"

TEMPLATES = [
   {
      "BACKEND": "django.template.backends.django.DjangoTemplates",
      "DIRS": (os.path.join(BASE_DIR, "templates"),),
      "APP_DIRS": True,
      "OPTIONS": {
         "context_processors": [
            "django.template.context_processors.debug",
            "django.template.context_processors.request",
            "django.contrib.auth.context_processors.auth",
            "django.contrib.messages.context_processors.messages",
         ]
      }
   }
]

WSGI_APPLICATION:str = "curaciones.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'mydatabase', # This is where you put the name of the db file. 
                 # If one doesn't exist, it will be created at migration time.
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS:List[Dict[str, str]] = [
   {
      "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
   },
   {
      "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
   },
   {
      "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
   },
   {
      "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
   }
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
LANGUAGE_CODE:str = "en-us"

TIME_ZONE:str = "UTC"

USE_I18N:bool = True

USE_TZ:bool = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
STATICFILES_DIRS:Tuple[str] = (os.path.join(BASE_DIR, "static"),)
STATIC_URL:str = "/static/"
STATIC_ROOT:str = "/static/"

# SASS, SCSS
STATICFILES_FINDERS:List[str] = [
   "django.contrib.staticfiles.finders.FileSystemFinder",
   "django.contrib.staticfiles.finders.AppDirectoriesFinder",
   "sass_processor.finders.CssFinder"
]
SASS_PROCESSOR_INCLUDE_DIRS:List[str] = [
   os.path.join(BASE_DIR, "extra-styles/scss"),
   os.path.join(BASE_DIR, "node_modules")
]
SASS_PROCESSOR_AUTO_INCLUDE:bool = False
SASS_PROCESSOR_INCLUDE_FILE_PATTERN:str = r"^.+\.scss$"
SASS_PRECISION:int = 8
SASS_OUTPUT_STYLE:str = "compact"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD:str = "django.db.models.BigAutoField"
